version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfiles/postgres/Dockerfile
    container_name: postgres
    shm_size: 512mb
    expose:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - BlogNetwork
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfiles/dev/backend/Dockerfile
    container_name: backend
    ports:
      - '6565:6565'
    environment:
      - DEBUG=True
      - SECRET_KEY=test
      - ALLOWED_HOSTS=*
    volumes:
      - ./:/app
    depends_on:
      - postgres
    networks:
      - BlogNetwork
    restart: always
  redis:
    container_name: redis
    build:
      context: .
      dockerfile: Dockerfiles/dev/redis/Dockerfile
    restart: always
    networks:
      - BlogNetwork
  worker:
    build:
      context: .
      dockerfile: Dockerfiles/dev/backend/Dockerfile
    command: celery -A core worker --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - redis
      - backend
    networks:
      - BlogNetwork

  beat:
    build:
      context: .
      dockerfile: Dockerfiles/dev/backend/Dockerfile
    command: celery -A core beat --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - redis
      - backend
    networks:
      - BlogNetwork


networks:
  BlogNetwork:
    name: BlogNetwork
