version: '3.8'
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfiles/action/backend/Dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - SECRET_KEY=test
      - ALLOWED_HOSTS=*
      - DATABASE_NAME=sqlite3
    volumes:
      - ./:/app
    networks:
      - BlogNetwork
    restart: always


networks:
  BlogNetwork:
    name: BlogNetwork