version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    shm_size: 512mb
    expose:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Blog
    networks:
      - BlogNetwork
    restart: unless-stopped

  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    environment:
      - DEBUG=True
      - SECRET_KEY=test
      - ALLOWED_HOSTS=*
    volumes:
      - ./:/app
    depends_on:
      - postgres
    networks:
      - BlogNetwork
    restart: always
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend

  beat:
    build: .
    command: celery -A core beat --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend


networks:
  BlogNetwork:
    name: BlogNetwork
