version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfiles/postgres/Dockerfile
    container_name: postgres
    shm_size: 512mb
    expose:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Blog
    networks:
      - BlogNetwork
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfiles/action/backend/Dockerfile
    container_name: backend
    command: python manage.py makemigrations && python manage.py migrate
    environment:
      - DEBUG=True
      - SECRET_KEY=test
      - ALLOWED_HOSTS=*
      - DATABASE_NAME=sqlite3
    volumes:
      - ./:/app
    depends_on:
      - postgres
    networks:
      - BlogNetwork
    restart: always


networks:
  BlogNetwork:
    name: BlogNetwork