# Use the official PostgreSQL image as a base
FROM postgres

# Set environment variables
ENV POSTGRES_USER: postgres
ENV POSTGRES_PASSWORD: 1234
ENV POSTGRES_DB: Blog

# Expose the PostgreSQL port
EXPOSE 5432
VOLUME ["/var/lib/postgresql/data"]
