name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and run services
        run: docker-compose -f docker-compose-git-action.yml up --build -d

      - name: Run Tests
        run: docker-compose -f docker-compose-git-action.yml exec -T backend pytest || docker-compose -f docker-compose-git-action.yml logs backend


